### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by webuniverseio** [thetangram/composer#1]
Hi, this is interesting project & I think you have good points for what service should do in description. Is this work in progress or you had to pause on it? There is not much description on how to use it. Did you end up using something else?

Thank you.

**Comment by jomoespe** [comment]
Hi @szarouski Right now it's not an usable version, but  I'm working in a full and deep project refactor. I hope I will upgrade to a new version soon.

**Comment by webuniverseio** [comment]
👍
